### ISSUE TITLE
Static Colliders

### ISSUE THREAD

**Issue by lewaxml** [z2oh/MegaManClone#13]
I know we want to use Controller2D instead of rigidbody, but this creates a back end problem. To quote the unity manual:
"The physics engine assumes that static colliders never move or change and can make useful optimizations based on this assumption. Consequently, static colliders should not be disabled/enabled, moved or scaled during gameplay.
 ...  
If you want a collider object that is not affected by incoming rigidbodies but can still be moved from a script then you should attach a Kinematic Rigidbody component to it rather than no Rigidbody at all."

**Comment by z2oh** [comment]
https://www.youtube.com/playlist?list=PLFt_AvWsXl0f0hqURlhyIoAabKPgRsqjz

This was the tutorial I followed to make the raytracing Controller2D. There is some other good stuff in there as well, and I'm sure it goes over how to solve this problem. It could very well be that rigidbodies still go on the objects, but that the gravity, etc. is all set to 0 as to not affect the actual physics.

**Comment by lewaxml** [comment]
Right from what I understand the fix is to just require a rigidbody 2D and call GetComponent<Rigidbody2D>().isKinematic = true at startup. I'll look through the video though, there may be another way to set colliders as non- static.
